---
- name: Bootstrap system
  command: apt-get -y update creates=/usr/share/doc/python-apt
- name: Bootstrap system
  command: apt-get -y install python-apt python-pycurl creates=/usr/share/doc/python-apt

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh
  when: disable_password_authentication

- name: Update APT package cache
  apt: update_cache=yes

- name: Install packages
  apt: pkg={{item}} state=installed
  with_items: default_packages

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present
  when: unattended_upgrades

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic
  when: unattended_upgrades

- name: Copy .bashrc for root
  copy: src=bashrc dest=/root/.bashrc owner=root

- name: Copy .bashrc for {{user}}
  copy: src=bashrc dest=/home/{{user}}/.bashrc owner={{user}}

- name: Make sure unattended-upgrades only installs from {{ansible_distribution_release}}-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="{{ansible_distribution_release}}-updates" state=absent
  when: unattended_upgrades

- name: Locale
  script: locale-install.sh {{locale}}

- name: set locale default
  template: src=locale dest=/etc/default/locale

- include: generate_ssh_pubkey.yml
